version: "2"
run:
  tests: true

linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gosec
    - nakedret
    - nolintlint
    - thelper
    - bidichk
    - gocheckcompilerdirectives
    - govet
    - ineffassign
    - mirror
    - misspell
    - reassign
    - revive # only certain checks enabled
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - whitespace

  settings:
    dogsled:
      max-blank-identifiers: 6
    gocritic:
      disabled-checks:
        - regexpMust
        - appendAssign
        - ifElseChain
    gosec:
      excludes:
        - G115
      confidence: medium
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    revive:
      rules:
        - name: redefines-builtin-id
          disabled: true
    staticcheck:
      checks:
        - all
    unused:
      local-variables-are-used: false

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: x/locking/keeper/keeper.go
        text: "SA1019: sdktypes.TimeKey is deprecated: exists only for state compatibility reasons, should not be used for new storage keys using time. Please use the time KeyCodec provided in the collections package."
    paths:
      - '\*\.pb\.go'
      - '\*\.pb\.gw\.go'
      - pkg/crypto/hash.go
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - '\*\.pb\.go'
      - '\*\.pb\.gw\.go'
