version: 1
validation: sovereign
accounts:
  - name: alice
    coins:
      - 1000gas
      - 1000bond
client:
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100bond
    home: "./tmp/alice"
    config:
      moniker: "alice"
    client:
      output: "json"
