// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: goat/relayer/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the relayer module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params   Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Relayer  *Relayer     `protobuf:"bytes,2,opt,name=relayer,proto3" json:"relayer,omitempty"`
	Sequence uint64       `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Voters   []*Voter     `protobuf:"bytes,4,rep,name=voters,proto3" json:"voters,omitempty"`
	Pubkeys  []*PublicKey `protobuf:"bytes,5,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	Randao   []byte       `protobuf:"bytes,6,opt,name=randao,proto3" json:"randao,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa9632e6094ae03c, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRelayer() *Relayer {
	if m != nil {
		return m.Relayer
	}
	return nil
}

func (m *GenesisState) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *GenesisState) GetVoters() []*Voter {
	if m != nil {
		return m.Voters
	}
	return nil
}

func (m *GenesisState) GetPubkeys() []*PublicKey {
	if m != nil {
		return m.Pubkeys
	}
	return nil
}

func (m *GenesisState) GetRandao() []byte {
	if m != nil {
		return m.Randao
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "goat.relayer.v1.GenesisState")
}

func init() { proto.RegisterFile("goat/relayer/v1/genesis.proto", fileDescriptor_aa9632e6094ae03c) }

var fileDescriptor_aa9632e6094ae03c = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xbd, 0x4e, 0xeb, 0x30,
	0x18, 0x8d, 0xdb, 0xde, 0xf4, 0xe2, 0x56, 0x42, 0x58, 0xa8, 0x58, 0x11, 0x84, 0x88, 0x29, 0x02,
	0xc9, 0x56, 0x0b, 0x13, 0x63, 0x25, 0xc4, 0xc0, 0x82, 0x8c, 0xc4, 0xc0, 0xe6, 0x14, 0x2b, 0x44,
	0x6d, 0xe3, 0xe0, 0x38, 0x85, 0xbc, 0x05, 0x23, 0x8f, 0xc0, 0xc8, 0x63, 0x74, 0xec, 0xc8, 0x84,
	0x50, 0x3b, 0xf0, 0x1a, 0x28, 0x4e, 0xda, 0xa1, 0x59, 0xac, 0xf3, 0xf9, 0xfc, 0x7c, 0x47, 0x36,
	0x3c, 0x0a, 0x25, 0xd7, 0x54, 0x89, 0x09, 0xcf, 0x85, 0xa2, 0xb3, 0x3e, 0x0d, 0x45, 0x2c, 0xd2,
	0x28, 0x25, 0x89, 0x92, 0x5a, 0xa2, 0xdd, 0x82, 0x26, 0x15, 0x4d, 0x66, 0x7d, 0x67, 0x8f, 0x4f,
	0xa3, 0x58, 0x52, 0x73, 0x96, 0x1a, 0xe7, 0x70, 0x3b, 0x22, 0xe1, 0x8a, 0x4f, 0xab, 0x04, 0xa7,
	0xb6, 0x60, 0x1d, 0x56, 0xd2, 0xfb, 0xa1, 0x0c, 0xa5, 0x81, 0xb4, 0x40, 0xe5, 0xed, 0xc9, 0x7b,
	0x03, 0x76, 0xaf, 0xcb, 0x22, 0x77, 0x9a, 0x6b, 0x81, 0x2e, 0xa1, 0x5d, 0xa6, 0x62, 0xe0, 0x01,
	0xbf, 0x33, 0x38, 0x20, 0x5b, 0xc5, 0xc8, 0xad, 0xa1, 0x87, 0x3b, 0xf3, 0xef, 0x63, 0xeb, 0xe3,
	0xf7, 0xf3, 0x14, 0xb0, 0xca, 0x81, 0x06, 0xb0, 0x5d, 0xe9, 0x70, 0xc3, 0x98, 0x71, 0xcd, 0xcc,
	0x4a, 0xc8, 0xd6, 0x42, 0xe4, 0xc0, 0xff, 0xa9, 0x78, 0xce, 0x44, 0x3c, 0x12, 0xb8, 0xe9, 0x01,
	0xbf, 0xc5, 0x36, 0x33, 0x22, 0xd0, 0x9e, 0x49, 0x2d, 0x54, 0x8a, 0x5b, 0x5e, 0xd3, 0xef, 0x0c,
	0x7a, 0xb5, 0xb8, 0xfb, 0x82, 0x66, 0x95, 0x0a, 0x5d, 0xc0, 0x76, 0x92, 0x05, 0x63, 0x91, 0xa7,
	0xf8, 0x9f, 0x31, 0x38, 0xf5, 0xf2, 0x59, 0x30, 0x89, 0x46, 0x37, 0x22, 0x67, 0x6b, 0x29, 0xea,
	0x41, 0x5b, 0xf1, 0xf8, 0x91, 0x4b, 0x6c, 0x7b, 0xc0, 0xef, 0xb2, 0x6a, 0x1a, 0x5e, 0xcd, 0x97,
	0x2e, 0x58, 0x2c, 0x5d, 0xf0, 0xb3, 0x74, 0xc1, 0xdb, 0xca, 0xb5, 0x16, 0x2b, 0xd7, 0xfa, 0x5a,
	0xb9, 0xd6, 0xc3, 0x59, 0x18, 0xe9, 0xa7, 0x2c, 0x20, 0x23, 0x39, 0xa5, 0xc5, 0x82, 0x58, 0xe8,
	0x17, 0xa9, 0xc6, 0x06, 0xd3, 0xd7, 0xcd, 0x17, 0xe8, 0x3c, 0x11, 0x69, 0x60, 0x9b, 0x87, 0x3e,
	0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xd1, 0x15, 0x41, 0x00, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Randao) > 0 {
		i -= len(m.Randao)
		copy(dAtA[i:], m.Randao)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Randao)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Pubkeys) > 0 {
		for iNdEx := len(m.Pubkeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Pubkeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Voters) > 0 {
		for iNdEx := len(m.Voters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Voters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Sequence != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Sequence))
		i--
		dAtA[i] = 0x18
	}
	if m.Relayer != nil {
		{
			size, err := m.Relayer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Relayer != nil {
		l = m.Relayer.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Sequence != 0 {
		n += 1 + sovGenesis(uint64(m.Sequence))
	}
	if len(m.Voters) > 0 {
		for _, e := range m.Voters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Pubkeys) > 0 {
		for _, e := range m.Pubkeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = len(m.Randao)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Relayer == nil {
				m.Relayer = &Relayer{}
			}
			if err := m.Relayer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sequence", wireType)
			}
			m.Sequence = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sequence |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voters = append(m.Voters, &Voter{})
			if err := m.Voters[len(m.Voters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkeys = append(m.Pubkeys, &PublicKey{})
			if err := m.Pubkeys[len(m.Pubkeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randao", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Randao = append(m.Randao[:0], dAtA[iNdEx:postIndex]...)
			if m.Randao == nil {
				m.Randao = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
