// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: goat/goat/v1/goat.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BlobsBundle is retrieved through engine-api from the execution layer client.
type BlobsBundle struct {
	// The KZG commitments of the blobs.
	KzgCommitments [][]byte `protobuf:"bytes,1,rep,name=kzg_commitments,json=kzgCommitments,proto3" json:"kzg_commitments,omitempty"`
	// The proofs of the blobs.
	Proofs [][]byte `protobuf:"bytes,2,rep,name=proofs,proto3" json:"proofs,omitempty"`
	// The blobs itself.
	Blobs [][]byte `protobuf:"bytes,3,rep,name=blobs,proto3" json:"blobs,omitempty"`
}

func (m *BlobsBundle) Reset()         { *m = BlobsBundle{} }
func (m *BlobsBundle) String() string { return proto.CompactTextString(m) }
func (*BlobsBundle) ProtoMessage()    {}
func (*BlobsBundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_e240fa210386b3d7, []int{0}
}
func (m *BlobsBundle) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlobsBundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlobsBundle.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlobsBundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlobsBundle.Merge(m, src)
}
func (m *BlobsBundle) XXX_Size() int {
	return m.Size()
}
func (m *BlobsBundle) XXX_DiscardUnknown() {
	xxx_messageInfo_BlobsBundle.DiscardUnknown(m)
}

var xxx_messageInfo_BlobsBundle proto.InternalMessageInfo

func (m *BlobsBundle) GetKzgCommitments() [][]byte {
	if m != nil {
		return m.KzgCommitments
	}
	return nil
}

func (m *BlobsBundle) GetProofs() [][]byte {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *BlobsBundle) GetBlobs() [][]byte {
	if m != nil {
		return m.Blobs
	}
	return nil
}

// ExecutionPayload
type ExecutionPayload struct {
	ParentHash    []byte   `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	FeeRecipient  []byte   `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty"`
	StateRoot     []byte   `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	ReceiptsRoot  []byte   `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty"`
	LogsBloom     []byte   `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty"`
	PrevRandao    []byte   `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty"`
	BlockNumber   uint64   `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit      uint64   `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64   `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp     uint64   `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte   `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	BaseFeePerGas []byte   `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	BlockHash     []byte   `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Transactions  [][]byte `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty"`
	BeaconRoot    []byte   `protobuf:"bytes,15,opt,name=beacon_root,json=beaconRoot,proto3" json:"beacon_root,omitempty"`
	BlobGasUsed   uint64   `protobuf:"varint,16,opt,name=blob_gas_used,json=blobGasUsed,proto3" json:"blob_gas_used,omitempty"`
	ExcessBlobGas uint64   `protobuf:"varint,17,opt,name=excess_blob_gas,json=excessBlobGas,proto3" json:"excess_blob_gas,omitempty"`
}

func (m *ExecutionPayload) Reset()         { *m = ExecutionPayload{} }
func (m *ExecutionPayload) String() string { return proto.CompactTextString(m) }
func (*ExecutionPayload) ProtoMessage()    {}
func (*ExecutionPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_e240fa210386b3d7, []int{1}
}
func (m *ExecutionPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecutionPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecutionPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecutionPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionPayload.Merge(m, src)
}
func (m *ExecutionPayload) XXX_Size() int {
	return m.Size()
}
func (m *ExecutionPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionPayload.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionPayload proto.InternalMessageInfo

func (m *ExecutionPayload) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *ExecutionPayload) GetFeeRecipient() []byte {
	if m != nil {
		return m.FeeRecipient
	}
	return nil
}

func (m *ExecutionPayload) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *ExecutionPayload) GetReceiptsRoot() []byte {
	if m != nil {
		return m.ReceiptsRoot
	}
	return nil
}

func (m *ExecutionPayload) GetLogsBloom() []byte {
	if m != nil {
		return m.LogsBloom
	}
	return nil
}

func (m *ExecutionPayload) GetPrevRandao() []byte {
	if m != nil {
		return m.PrevRandao
	}
	return nil
}

func (m *ExecutionPayload) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ExecutionPayload) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *ExecutionPayload) GetGasUsed() uint64 {
	if m != nil {
		return m.GasUsed
	}
	return 0
}

func (m *ExecutionPayload) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ExecutionPayload) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *ExecutionPayload) GetBaseFeePerGas() []byte {
	if m != nil {
		return m.BaseFeePerGas
	}
	return nil
}

func (m *ExecutionPayload) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *ExecutionPayload) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *ExecutionPayload) GetBeaconRoot() []byte {
	if m != nil {
		return m.BeaconRoot
	}
	return nil
}

func (m *ExecutionPayload) GetBlobGasUsed() uint64 {
	if m != nil {
		return m.BlobGasUsed
	}
	return 0
}

func (m *ExecutionPayload) GetExcessBlobGas() uint64 {
	if m != nil {
		return m.ExcessBlobGas
	}
	return 0
}

func init() {
	proto.RegisterType((*BlobsBundle)(nil), "goat.goat.v1.BlobsBundle")
	proto.RegisterType((*ExecutionPayload)(nil), "goat.goat.v1.ExecutionPayload")
}

func init() { proto.RegisterFile("goat/goat/v1/goat.proto", fileDescriptor_e240fa210386b3d7) }

var fileDescriptor_e240fa210386b3d7 = []byte{
	// 524 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xeb, 0x36, 0x4d, 0x9b, 0x8d, 0xd3, 0x84, 0x15, 0x82, 0x45, 0x50, 0x13, 0x82, 0x44,
	0x73, 0x2a, 0xaa, 0x78, 0x03, 0xf3, 0x51, 0x0e, 0x08, 0x55, 0x96, 0xb8, 0x70, 0x59, 0x8d, 0xed,
	0x89, 0x63, 0xc5, 0xf6, 0x5a, 0xbb, 0x9b, 0x90, 0xf6, 0x29, 0x78, 0x2c, 0x2e, 0x48, 0x3d, 0x72,
	0x44, 0xc9, 0x8b, 0xa0, 0x9d, 0x4d, 0x5b, 0x71, 0xd9, 0x8f, 0xdf, 0xfc, 0x35, 0x9a, 0xf9, 0xcf,
	0x2e, 0x7b, 0x5a, 0x28, 0xb0, 0x6f, 0x69, 0x59, 0x5d, 0xd0, 0x7e, 0xde, 0x6a, 0x65, 0x15, 0x0f,
	0xe9, 0x4c, 0xcb, 0xea, 0x62, 0x92, 0xb3, 0x7e, 0x5c, 0xa9, 0xd4, 0xc4, 0xcb, 0x26, 0xaf, 0x90,
	0x9f, 0xb1, 0xe1, 0xe2, 0xa6, 0x90, 0x99, 0xaa, 0xeb, 0xd2, 0xd6, 0xd8, 0x58, 0x23, 0x82, 0xf1,
	0xc1, 0x34, 0x4c, 0x4e, 0x16, 0x37, 0xc5, 0xfb, 0x07, 0xca, 0x9f, 0xb0, 0x6e, 0xab, 0x95, 0x9a,
	0x19, 0xb1, 0x4f, 0xf1, 0xdd, 0x8d, 0x3f, 0x66, 0x87, 0xa9, 0xcb, 0x27, 0x0e, 0x08, 0xfb, 0xcb,
	0xe4, 0x77, 0x87, 0x8d, 0x3e, 0xae, 0x31, 0x5b, 0xda, 0x52, 0x35, 0x57, 0x70, 0x5d, 0x29, 0xc8,
	0xf9, 0x4b, 0xd6, 0x6f, 0x41, 0x63, 0x63, 0xe5, 0x1c, 0xcc, 0x5c, 0x04, 0xe3, 0x60, 0x1a, 0x26,
	0xcc, 0xa3, 0xcf, 0x60, 0xe6, 0xfc, 0x35, 0x1b, 0xcc, 0x10, 0xa5, 0xc6, 0xac, 0x6c, 0x4b, 0x6c,
	0xac, 0xd8, 0x27, 0x49, 0x38, 0x43, 0x4c, 0xee, 0x18, 0x3f, 0x65, 0xcc, 0x58, 0xb0, 0x28, 0xb5,
	0x52, 0x56, 0x1c, 0x90, 0xa2, 0x47, 0x24, 0x51, 0xca, 0xba, 0x1c, 0x1a, 0x33, 0x2c, 0x5b, 0x6b,
	0xbc, 0xa2, 0xe3, 0x73, 0xdc, 0x41, 0x12, 0x9d, 0x32, 0x56, 0xa9, 0xc2, 0xc8, 0xb4, 0x52, 0xaa,
	0x16, 0x87, 0x3e, 0x87, 0x23, 0xb1, 0x03, 0x54, 0xa8, 0xc6, 0x95, 0xd4, 0xd0, 0xe4, 0xa0, 0x44,
	0x77, 0x57, 0xa8, 0xc6, 0x55, 0x42, 0x84, 0xbf, 0x62, 0x61, 0x5a, 0xa9, 0x6c, 0x21, 0x9b, 0x65,
	0x9d, 0xa2, 0x16, 0x47, 0xe3, 0x60, 0xda, 0x49, 0xfa, 0xc4, 0xbe, 0x12, 0xe2, 0xcf, 0x59, 0xaf,
	0x00, 0x23, 0xab, 0xb2, 0x2e, 0xad, 0x38, 0xa6, 0xf8, 0x71, 0x01, 0xe6, 0x8b, 0xbb, 0xf3, 0x67,
	0xcc, 0x9d, 0xe5, 0xd2, 0x60, 0x2e, 0x7a, 0x14, 0x3b, 0x2a, 0xc0, 0x7c, 0x33, 0x98, 0xf3, 0x17,
	0xac, 0x67, 0xcb, 0x1a, 0x8d, 0x85, 0xba, 0x15, 0x8c, 0x62, 0x0f, 0xc0, 0x15, 0x8e, 0x6b, 0xab,
	0x41, 0xe6, 0x60, 0x41, 0xf4, 0x7d, 0xe1, 0x44, 0x3e, 0x80, 0x05, 0x7e, 0xc6, 0x46, 0x29, 0x18,
	0x94, 0xce, 0xc5, 0x16, 0xb5, 0x2c, 0xc0, 0x88, 0x90, 0x44, 0x03, 0xc7, 0x3f, 0x21, 0x5e, 0xa1,
	0xbe, 0x04, 0xe3, 0xf2, 0xf8, 0x06, 0x68, 0x12, 0x03, 0x9f, 0x87, 0x08, 0x0d, 0x62, 0xc2, 0x42,
	0xab, 0xa1, 0x31, 0x90, 0xb9, 0xf9, 0x19, 0x71, 0x42, 0xb3, 0xfd, 0x8f, 0x39, 0x93, 0x52, 0x84,
	0x4c, 0x35, 0xde, 0xe6, 0xa1, 0x37, 0xc9, 0x23, 0x32, 0x79, 0xc2, 0x06, 0xee, 0x31, 0xc8, 0xfb,
	0x4e, 0x47, 0xf7, 0x2e, 0xa5, 0x97, 0xbb, 0x6e, 0xdf, 0xb0, 0x21, 0xae, 0x33, 0x34, 0x34, 0x0a,
	0x92, 0x8a, 0x47, 0xa4, 0x1a, 0x78, 0x1c, 0x7b, 0x6d, 0x1c, 0xff, 0xda, 0x44, 0xc1, 0xed, 0x26,
	0x0a, 0xfe, 0x6e, 0xa2, 0xe0, 0xe7, 0x36, 0xda, 0xbb, 0xdd, 0x46, 0x7b, 0x7f, 0xb6, 0xd1, 0xde,
	0xf7, 0x69, 0x51, 0xda, 0xf9, 0x32, 0x3d, 0xcf, 0x54, 0x4d, 0x8f, 0xbe, 0x41, 0xfb, 0x43, 0xe9,
	0x85, 0xff, 0x08, 0x6b, 0xbf, 0xd9, 0xeb, 0x16, 0x4d, 0xda, 0xa5, 0xef, 0xf0, 0xee, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd4, 0x7c, 0xa9, 0x25, 0x29, 0x03, 0x00, 0x00,
}

func (m *BlobsBundle) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlobsBundle) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlobsBundle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Blobs) > 0 {
		for iNdEx := len(m.Blobs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Blobs[iNdEx])
			copy(dAtA[i:], m.Blobs[iNdEx])
			i = encodeVarintGoat(dAtA, i, uint64(len(m.Blobs[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Proofs) > 0 {
		for iNdEx := len(m.Proofs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proofs[iNdEx])
			copy(dAtA[i:], m.Proofs[iNdEx])
			i = encodeVarintGoat(dAtA, i, uint64(len(m.Proofs[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.KzgCommitments) > 0 {
		for iNdEx := len(m.KzgCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.KzgCommitments[iNdEx])
			copy(dAtA[i:], m.KzgCommitments[iNdEx])
			i = encodeVarintGoat(dAtA, i, uint64(len(m.KzgCommitments[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ExecutionPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecutionPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecutionPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExcessBlobGas != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.ExcessBlobGas))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.BlobGasUsed != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.BlobGasUsed))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.BeaconRoot) > 0 {
		i -= len(m.BeaconRoot)
		copy(dAtA[i:], m.BeaconRoot)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.BeaconRoot)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Transactions) > 0 {
		for iNdEx := len(m.Transactions) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Transactions[iNdEx])
			copy(dAtA[i:], m.Transactions[iNdEx])
			i = encodeVarintGoat(dAtA, i, uint64(len(m.Transactions[iNdEx])))
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.BaseFeePerGas) > 0 {
		i -= len(m.BaseFeePerGas)
		copy(dAtA[i:], m.BaseFeePerGas)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.BaseFeePerGas)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.ExtraData) > 0 {
		i -= len(m.ExtraData)
		copy(dAtA[i:], m.ExtraData)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.ExtraData)))
		i--
		dAtA[i] = 0x5a
	}
	if m.Timestamp != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x50
	}
	if m.GasUsed != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.GasUsed))
		i--
		dAtA[i] = 0x48
	}
	if m.GasLimit != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x40
	}
	if m.BlockNumber != 0 {
		i = encodeVarintGoat(dAtA, i, uint64(m.BlockNumber))
		i--
		dAtA[i] = 0x38
	}
	if len(m.PrevRandao) > 0 {
		i -= len(m.PrevRandao)
		copy(dAtA[i:], m.PrevRandao)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.PrevRandao)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.LogsBloom) > 0 {
		i -= len(m.LogsBloom)
		copy(dAtA[i:], m.LogsBloom)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.LogsBloom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReceiptsRoot) > 0 {
		i -= len(m.ReceiptsRoot)
		copy(dAtA[i:], m.ReceiptsRoot)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.ReceiptsRoot)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FeeRecipient) > 0 {
		i -= len(m.FeeRecipient)
		copy(dAtA[i:], m.FeeRecipient)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.FeeRecipient)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParentHash) > 0 {
		i -= len(m.ParentHash)
		copy(dAtA[i:], m.ParentHash)
		i = encodeVarintGoat(dAtA, i, uint64(len(m.ParentHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGoat(dAtA []byte, offset int, v uint64) int {
	offset -= sovGoat(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BlobsBundle) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.KzgCommitments) > 0 {
		for _, b := range m.KzgCommitments {
			l = len(b)
			n += 1 + l + sovGoat(uint64(l))
		}
	}
	if len(m.Proofs) > 0 {
		for _, b := range m.Proofs {
			l = len(b)
			n += 1 + l + sovGoat(uint64(l))
		}
	}
	if len(m.Blobs) > 0 {
		for _, b := range m.Blobs {
			l = len(b)
			n += 1 + l + sovGoat(uint64(l))
		}
	}
	return n
}

func (m *ExecutionPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParentHash)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.FeeRecipient)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.ReceiptsRoot)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.LogsBloom)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.PrevRandao)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	if m.BlockNumber != 0 {
		n += 1 + sovGoat(uint64(m.BlockNumber))
	}
	if m.GasLimit != 0 {
		n += 1 + sovGoat(uint64(m.GasLimit))
	}
	if m.GasUsed != 0 {
		n += 1 + sovGoat(uint64(m.GasUsed))
	}
	if m.Timestamp != 0 {
		n += 1 + sovGoat(uint64(m.Timestamp))
	}
	l = len(m.ExtraData)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.BaseFeePerGas)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	if len(m.Transactions) > 0 {
		for _, b := range m.Transactions {
			l = len(b)
			n += 1 + l + sovGoat(uint64(l))
		}
	}
	l = len(m.BeaconRoot)
	if l > 0 {
		n += 1 + l + sovGoat(uint64(l))
	}
	if m.BlobGasUsed != 0 {
		n += 2 + sovGoat(uint64(m.BlobGasUsed))
	}
	if m.ExcessBlobGas != 0 {
		n += 2 + sovGoat(uint64(m.ExcessBlobGas))
	}
	return n
}

func sovGoat(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGoat(x uint64) (n int) {
	return sovGoat(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BlobsBundle) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGoat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlobsBundle: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlobsBundle: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KzgCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KzgCommitments = append(m.KzgCommitments, make([]byte, postIndex-iNdEx))
			copy(m.KzgCommitments[len(m.KzgCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proofs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proofs = append(m.Proofs, make([]byte, postIndex-iNdEx))
			copy(m.Proofs[len(m.Proofs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Blobs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Blobs = append(m.Blobs, make([]byte, postIndex-iNdEx))
			copy(m.Blobs[len(m.Blobs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGoat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGoat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecutionPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGoat
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecutionPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecutionPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentHash = append(m.ParentHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ParentHash == nil {
				m.ParentHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeRecipient", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeRecipient = append(m.FeeRecipient[:0], dAtA[iNdEx:postIndex]...)
			if m.FeeRecipient == nil {
				m.FeeRecipient = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReceiptsRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReceiptsRoot = append(m.ReceiptsRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ReceiptsRoot == nil {
				m.ReceiptsRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogsBloom", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LogsBloom = append(m.LogsBloom[:0], dAtA[iNdEx:postIndex]...)
			if m.LogsBloom == nil {
				m.LogsBloom = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrevRandao", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrevRandao = append(m.PrevRandao[:0], dAtA[iNdEx:postIndex]...)
			if m.PrevRandao == nil {
				m.PrevRandao = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNumber", wireType)
			}
			m.BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNumber |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUsed", wireType)
			}
			m.GasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasUsed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtraData = append(m.ExtraData[:0], dAtA[iNdEx:postIndex]...)
			if m.ExtraData == nil {
				m.ExtraData = []byte{}
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseFeePerGas = append(m.BaseFeePerGas[:0], dAtA[iNdEx:postIndex]...)
			if m.BaseFeePerGas == nil {
				m.BaseFeePerGas = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transactions", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Transactions = append(m.Transactions, make([]byte, postIndex-iNdEx))
			copy(m.Transactions[len(m.Transactions)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeaconRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGoat
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGoat
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeaconRoot = append(m.BeaconRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.BeaconRoot == nil {
				m.BeaconRoot = []byte{}
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlobGasUsed", wireType)
			}
			m.BlobGasUsed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlobGasUsed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExcessBlobGas", wireType)
			}
			m.ExcessBlobGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExcessBlobGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGoat(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGoat
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGoat(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGoat
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGoat
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGoat
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGoat
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGoat
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGoat        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGoat          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGoat = fmt.Errorf("proto: unexpected end of group")
)
