name: mainnet

services:
  geth:
    image: ghcr.io/goatnetwork/goat-geth:v0.1.2
    restart: unless-stopped
    stop_grace_period: 30s
    command:
      - --goat=mainnet
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      # Open it if you need an archive node
      # - --gcmode=archive
    volumes:
      - /data/geth:/root/.ethereum
    ports:
      - 8545:8545
      - 8546:8546
    logging:
      driver: local

  goat:
    image: ghcr.io/goatnetwork/goat:v0.1.2
    restart: unless-stopped
    stop_grace_period: 30s
    command:
      - start
      - --goat.geth=/geth/geth.ipc
      - --chain-id=goat-mainnet
      - --grpc.address=0.0.0.0:9090
      - --api.enable
      - --api.address=tcp://0.0.0.0:1317
    ports:
      - 1317:1317
      - 9090:9090
    depends_on:
      - geth
    volumes:
      - /data/goat:/root/.goat
      - /data/geth:/geth
    logging:
      driver: local
