// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: goat/locking/v1/locking.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorStatus is the status of a validator.
type ValidatorStatus int32

const (
	// UNSPECIFIED defines an invalid validator status.
	ValidatorStatus_Unspecified ValidatorStatus = 0
	// Pending means the validator is waitting for
	ValidatorStatus_Pending ValidatorStatus = 1
	// Active means the validator is producing and voting new blocks
	ValidatorStatus_Active ValidatorStatus = 2
	// Tombstoned means the validator did malicious behaviors like double sign and
	// killed out
	ValidatorStatus_Tombstoned ValidatorStatus = 3
	// Downgrade means the validator is offline
	ValidatorStatus_Downgrade ValidatorStatus = 4
	// Inactive means the validator is exiting in progress or exited
	ValidatorStatus_Inactive ValidatorStatus = 5
)

var ValidatorStatus_name = map[int32]string{
	0: "VALIDATOR_STATUS_UNSPECIFIED",
	1: "VALIDATOR_STATUS_PENDING",
	2: "VALIDATOR_STATUS_ACTIVE",
	3: "VALIDATOR_STATUS_TOMBSTONED",
	4: "VALIDATOR_STATUS_DOWNGRADE",
	5: "VALIDATOR_STATUS_INACTIVE",
}

var ValidatorStatus_value = map[string]int32{
	"VALIDATOR_STATUS_UNSPECIFIED": 0,
	"VALIDATOR_STATUS_PENDING":     1,
	"VALIDATOR_STATUS_ACTIVE":      2,
	"VALIDATOR_STATUS_TOMBSTONED":  3,
	"VALIDATOR_STATUS_DOWNGRADE":   4,
	"VALIDATOR_STATUS_INACTIVE":    5,
}

func (x ValidatorStatus) String() string {
	return proto.EnumName(ValidatorStatus_name, int32(x))
}

func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3aad17b4b53f2480, []int{0}
}

// Validator
type Validator struct {
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Power  uint64 `protobuf:"varint,2,opt,name=power,proto3" json:"power,omitempty"`
	// the total locking
	Locking github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=locking,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"locking"`
	// unclaimed goat reward
	GoatReward cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=goat_reward,json=goatReward,proto3,customtype=cosmossdk.io/math.Int" json:"goat_reward"`
	// unclaimed gas fee rewrad
	GasReward cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=gas_reward,json=gasReward,proto3,customtype=cosmossdk.io/math.Int" json:"gas_reward"`
	Status    ValidatorStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=goat.locking.v1.ValidatorStatus" json:"status,omitempty"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aad17b4b53f2480, []int{0}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

func (m *Validator) GetPower() uint64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *Validator) GetLocking() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Locking
	}
	return nil
}

func (m *Validator) GetStatus() ValidatorStatus {
	if m != nil {
		return m.Status
	}
	return ValidatorStatus_Unspecified
}

// SigningInfo
type SigningInfo struct {
	// Height at which validator was first a candidate OR was un-jailed
	StartHeight int64 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// Timestamp until which the validator is jailed due to liveness downtime.
	JailedUntil time.Time `protobuf:"bytes,2,opt,name=jailed_until,json=jailedUntil,proto3,stdtime" json:"jailed_until"`
	// A counter of missed (unsigned) blocks. It is used to avoid unnecessary
	// reads in the missed block bitmap.
	MissedBlocksCounter int64 `protobuf:"varint,3,opt,name=missed_blocks_counter,json=missedBlocksCounter,proto3" json:"missed_blocks_counter,omitempty"`
}

func (m *SigningInfo) Reset()         { *m = SigningInfo{} }
func (m *SigningInfo) String() string { return proto.CompactTextString(m) }
func (*SigningInfo) ProtoMessage()    {}
func (*SigningInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3aad17b4b53f2480, []int{1}
}
func (m *SigningInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SigningInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SigningInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SigningInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningInfo.Merge(m, src)
}
func (m *SigningInfo) XXX_Size() int {
	return m.Size()
}
func (m *SigningInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SigningInfo proto.InternalMessageInfo

func (m *SigningInfo) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *SigningInfo) GetJailedUntil() time.Time {
	if m != nil {
		return m.JailedUntil
	}
	return time.Time{}
}

func (m *SigningInfo) GetMissedBlocksCounter() int64 {
	if m != nil {
		return m.MissedBlocksCounter
	}
	return 0
}

func init() {
	proto.RegisterEnum("goat.locking.v1.ValidatorStatus", ValidatorStatus_name, ValidatorStatus_value)
	proto.RegisterType((*Validator)(nil), "goat.locking.v1.Validator")
	proto.RegisterType((*SigningInfo)(nil), "goat.locking.v1.SigningInfo")
}

func init() { proto.RegisterFile("goat/locking/v1/locking.proto", fileDescriptor_3aad17b4b53f2480) }

var fileDescriptor_3aad17b4b53f2480 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x3f, 0x6f, 0xfb, 0x44,
	0x18, 0x8e, 0x93, 0x34, 0x25, 0xe7, 0xb4, 0x0d, 0xa6, 0x85, 0xd4, 0x40, 0x62, 0xba, 0x10, 0x5a,
	0xd5, 0x56, 0x82, 0x90, 0x10, 0x5b, 0xfe, 0x51, 0x8c, 0x4a, 0x52, 0x39, 0x4e, 0x91, 0x58, 0xac,
	0x73, 0x7c, 0x75, 0xae, 0x89, 0xef, 0x22, 0xdf, 0x25, 0xa1, 0x5f, 0x21, 0x53, 0xbf, 0x40, 0x24,
	0x16, 0x24, 0xc4, 0xc4, 0xc0, 0xc0, 0x47, 0xe8, 0x58, 0x31, 0x21, 0x86, 0x16, 0xb5, 0x03, 0x7c,
	0x05, 0x36, 0xe4, 0xb3, 0x53, 0xa1, 0x66, 0xfa, 0x2d, 0xc9, 0xbd, 0xef, 0xf3, 0x3c, 0xaf, 0x9f,
	0xbb, 0xc7, 0x67, 0xf0, 0xa1, 0x4f, 0x21, 0x37, 0x26, 0x74, 0x38, 0xc6, 0xc4, 0x37, 0xe6, 0xb5,
	0xf5, 0x52, 0x9f, 0x86, 0x94, 0x53, 0x65, 0x2f, 0x82, 0xf5, 0x75, 0x6f, 0x5e, 0x53, 0xdf, 0x86,
	0x01, 0x26, 0xd4, 0x10, 0xbf, 0x31, 0x47, 0x2d, 0x0f, 0x29, 0x0b, 0x28, 0x33, 0x5c, 0xc8, 0x90,
	0x31, 0xaf, 0xb9, 0x88, 0xc3, 0x9a, 0x31, 0xa4, 0x98, 0x24, 0xf8, 0x61, 0x8c, 0x3b, 0xa2, 0x32,
	0xe2, 0x22, 0x81, 0xf6, 0x7d, 0xea, 0xd3, 0xb8, 0x1f, 0xad, 0x92, 0x6e, 0xc5, 0xa7, 0xd4, 0x9f,
	0x20, 0x43, 0x54, 0xee, 0xec, 0xca, 0xe0, 0x38, 0x40, 0x8c, 0xc3, 0x60, 0x1a, 0x13, 0x8e, 0xfe,
	0x4d, 0x83, 0xfc, 0x25, 0x9c, 0x60, 0x0f, 0x72, 0x1a, 0x2a, 0xef, 0x82, 0xdc, 0x74, 0xe6, 0x8e,
	0xd1, 0x4d, 0x49, 0xd2, 0xa4, 0x6a, 0xc1, 0x4a, 0x2a, 0x65, 0x1f, 0x6c, 0x4d, 0xe9, 0x02, 0x85,
	0xa5, 0xb4, 0x26, 0x55, 0xb3, 0x56, 0x5c, 0x28, 0xd7, 0x60, 0x3b, 0xd9, 0x4e, 0x29, 0xa3, 0x65,
	0xaa, 0x72, 0xfd, 0x50, 0x4f, 0x2c, 0x45, 0xfe, 0xf5, 0xc4, 0xbf, 0xde, 0xa2, 0x98, 0x34, 0x3f,
	0xbb, 0x7b, 0xa8, 0xa4, 0x7e, 0x7e, 0xac, 0x54, 0x7d, 0xcc, 0x47, 0x33, 0x57, 0x1f, 0xd2, 0x20,
	0xf1, 0x9f, 0xfc, 0x9d, 0x32, 0x6f, 0x6c, 0xf0, 0x9b, 0x29, 0x62, 0x42, 0xc0, 0x7e, 0xfa, 0xfb,
	0x97, 0x63, 0xc9, 0x5a, 0x3f, 0x40, 0x39, 0x07, 0x72, 0x74, 0x7e, 0x4e, 0x88, 0x16, 0x30, 0xf4,
	0x4a, 0x59, 0x4d, 0xaa, 0xe6, 0x9b, 0x27, 0xd1, 0xd0, 0x3f, 0x1f, 0x2a, 0x07, 0xf1, 0x08, 0xe6,
	0x8d, 0x75, 0x4c, 0x8d, 0x00, 0xf2, 0x91, 0x6e, 0x12, 0xfe, 0xfb, 0xaf, 0xa7, 0x20, 0xf1, 0x63,
	0x12, 0x6e, 0x81, 0x48, 0x6f, 0x09, 0xb9, 0xf2, 0x35, 0x00, 0x3e, 0x64, 0xeb, 0x61, 0x5b, 0x6f,
	0x3e, 0x2c, 0xef, 0x43, 0x96, 0xcc, 0xfa, 0x1c, 0xe4, 0x18, 0x87, 0x7c, 0xc6, 0x4a, 0x39, 0x4d,
	0xaa, 0xee, 0xd6, 0x35, 0xfd, 0x55, 0xd0, 0xfa, 0xcb, 0xf9, 0xf6, 0x05, 0xcf, 0x4a, 0xf8, 0x47,
	0xbf, 0x49, 0x40, 0xee, 0x63, 0x9f, 0x60, 0xe2, 0x9b, 0xe4, 0x8a, 0x2a, 0x1f, 0x81, 0x02, 0xe3,
	0x30, 0xe4, 0xce, 0x08, 0x61, 0x7f, 0xc4, 0x45, 0x06, 0x19, 0x4b, 0x16, 0xbd, 0xaf, 0x44, 0x4b,
	0x39, 0x07, 0x85, 0x6b, 0x88, 0x27, 0xc8, 0x73, 0x66, 0x84, 0xe3, 0x89, 0xc8, 0x43, 0xae, 0xab,
	0x7a, 0x1c, 0xb3, 0xbe, 0x8e, 0x59, 0xb7, 0xd7, 0x31, 0x37, 0x77, 0xa2, 0x6d, 0xdd, 0x3e, 0x56,
	0xa4, 0xf8, 0x40, 0xe5, 0x58, 0x3e, 0x88, 0xd4, 0x4a, 0x1d, 0x1c, 0x04, 0x98, 0x31, 0xe4, 0x39,
	0x6e, 0x64, 0x97, 0x39, 0x43, 0x3a, 0x23, 0x1c, 0x85, 0xa5, 0x8c, 0x78, 0xf2, 0x3b, 0x31, 0xd8,
	0x14, 0x58, 0x2b, 0x86, 0xbe, 0xc8, 0xfe, 0xf3, 0x43, 0x45, 0x3a, 0xfe, 0x31, 0x0d, 0xf6, 0x5e,
	0x6d, 0x4b, 0xa9, 0x81, 0x0f, 0x2e, 0x1b, 0xe7, 0x66, 0xbb, 0x61, 0xf7, 0x2c, 0xa7, 0x6f, 0x37,
	0xec, 0x41, 0xdf, 0x19, 0x74, 0xfb, 0x17, 0x9d, 0x96, 0xf9, 0xa5, 0xd9, 0x69, 0x17, 0x53, 0xea,
	0xde, 0x72, 0xa5, 0xc9, 0x03, 0xc2, 0xa6, 0x68, 0x88, 0xaf, 0x30, 0xf2, 0x94, 0x4f, 0x40, 0x69,
	0x43, 0x72, 0xd1, 0xe9, 0xb6, 0xcd, 0xee, 0x59, 0x51, 0x52, 0xe5, 0xe5, 0x4a, 0xdb, 0xbe, 0x40,
	0xc4, 0x8b, 0x5e, 0x80, 0x8f, 0xc1, 0x7b, 0x1b, 0xd4, 0x46, 0xcb, 0x36, 0x2f, 0x3b, 0xc5, 0xb4,
	0x0a, 0x96, 0x2b, 0x2d, 0xd7, 0x18, 0x72, 0x3c, 0x47, 0x8a, 0x01, 0xde, 0xdf, 0x20, 0xda, 0xbd,
	0x6f, 0x9a, 0x7d, 0xbb, 0xd7, 0xed, 0xb4, 0x8b, 0x19, 0x75, 0x77, 0xb9, 0xd2, 0x80, 0x4d, 0x03,
	0x97, 0x71, 0x4a, 0x90, 0xa7, 0x9c, 0x02, 0x75, 0x43, 0xd0, 0xee, 0x7d, 0xdb, 0x3d, 0xb3, 0x1a,
	0xed, 0x4e, 0x31, 0xab, 0xee, 0x2c, 0x57, 0x5a, 0xbe, 0x4d, 0x17, 0xc4, 0x0f, 0xa1, 0x87, 0x94,
	0x13, 0x70, 0xb8, 0x41, 0x37, 0xbb, 0x89, 0x95, 0x2d, 0xb5, 0xb0, 0x5c, 0x69, 0x6f, 0x99, 0x04,
	0x0a, 0x33, 0xcd, 0xce, 0xdd, 0x53, 0x59, 0xba, 0x7f, 0x2a, 0x4b, 0x7f, 0x3d, 0x95, 0xa5, 0xdb,
	0xe7, 0x72, 0xea, 0xfe, 0xb9, 0x9c, 0xfa, 0xe3, 0xb9, 0x9c, 0xfa, 0xee, 0xe4, 0x7f, 0x17, 0x21,
	0x7a, 0x61, 0x08, 0xe2, 0x0b, 0x1a, 0x8e, 0xc5, 0xda, 0xf8, 0xfe, 0xe5, 0x33, 0x22, 0x6e, 0x84,
	0x9b, 0x13, 0xc1, 0x7e, 0xfa, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xd7, 0xaf, 0x36, 0x63,
	0x04, 0x00, 0x00,
}

func (this *SigningInfo) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SigningInfo)
	if !ok {
		that2, ok := that.(SigningInfo)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StartHeight != that1.StartHeight {
		return false
	}
	if !this.JailedUntil.Equal(that1.JailedUntil) {
		return false
	}
	if this.MissedBlocksCounter != that1.MissedBlocksCounter {
		return false
	}
	return true
}
func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintLocking(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.GasReward.Size()
		i -= size
		if _, err := m.GasReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLocking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.GoatReward.Size()
		i -= size
		if _, err := m.GoatReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLocking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Locking) > 0 {
		for iNdEx := len(m.Locking) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Locking[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLocking(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Power != 0 {
		i = encodeVarintLocking(dAtA, i, uint64(m.Power))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Pubkey) > 0 {
		i -= len(m.Pubkey)
		copy(dAtA[i:], m.Pubkey)
		i = encodeVarintLocking(dAtA, i, uint64(len(m.Pubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SigningInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SigningInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SigningInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MissedBlocksCounter != 0 {
		i = encodeVarintLocking(dAtA, i, uint64(m.MissedBlocksCounter))
		i--
		dAtA[i] = 0x18
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.JailedUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.JailedUntil):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintLocking(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if m.StartHeight != 0 {
		i = encodeVarintLocking(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLocking(dAtA []byte, offset int, v uint64) int {
	offset -= sovLocking(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pubkey)
	if l > 0 {
		n += 1 + l + sovLocking(uint64(l))
	}
	if m.Power != 0 {
		n += 1 + sovLocking(uint64(m.Power))
	}
	if len(m.Locking) > 0 {
		for _, e := range m.Locking {
			l = e.Size()
			n += 1 + l + sovLocking(uint64(l))
		}
	}
	l = m.GoatReward.Size()
	n += 1 + l + sovLocking(uint64(l))
	l = m.GasReward.Size()
	n += 1 + l + sovLocking(uint64(l))
	if m.Status != 0 {
		n += 1 + sovLocking(uint64(m.Status))
	}
	return n
}

func (m *SigningInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartHeight != 0 {
		n += 1 + sovLocking(uint64(m.StartHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.JailedUntil)
	n += 1 + l + sovLocking(uint64(l))
	if m.MissedBlocksCounter != 0 {
		n += 1 + sovLocking(uint64(m.MissedBlocksCounter))
	}
	return n
}

func sovLocking(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLocking(x uint64) (n int) {
	return sovLocking(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLocking
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthLocking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pubkey = append(m.Pubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.Pubkey == nil {
				m.Pubkey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			m.Power = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Power |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locking", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Locking = append(m.Locking, types.Coin{})
			if err := m.Locking[len(m.Locking)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoatReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GoatReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLocking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ValidatorStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLocking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SigningInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SigningInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SigningInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JailedUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLocking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLocking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.JailedUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedBlocksCounter", wireType)
			}
			m.MissedBlocksCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MissedBlocksCounter |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLocking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLocking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLocking(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLocking
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLocking
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLocking
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLocking
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLocking        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLocking          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLocking = fmt.Errorf("proto: unexpected end of group")
)
